INSERT INTO `tbarea` (`cod_area`, `nome_area`)
VALUES (1, "Política"),
  (2, "Ocultismo"),
  (3, "Romance"),
  (4, "Religião"),
  (5, "Sociologia"),
  (6, "Saúde"),
  (7, "Teatro"),
  (8, "Economia"),
  (9, "Economia"),
  (10, "Não-ficção");
INSERT INTO `tbarea` (`cod_area`, `nome_area`)
VALUES (11, "Saúde"),
  (12, "Aventura"),
  (13, "Religião"),
  (14, "Jornalismo"),
  (15, "Arte"),
  (16, "Teatro"),
  (17, "Biografia"),
  (18, "Moda"),
  (19, "Gastronomia"),
  (20, "Nutrição");
INSERT INTO `tbarea` (`cod_area`, `nome_area`)
VALUES (21, "Tricô"),
  (22, "Escultura"),
  (23, "Saúde"),
  (24, "Folclore"),
  (25, "Saúde"),
  (26, "Informática"),
  (27, "Cerâmica"),
  (28, "Zoologia"),
  (29, "Música"),
  (30, "Nutrição");
INSERT INTO `tbarea` (`cod_area`, `nome_area`)
VALUES (31, "Mitologia"),
  (32, "Física"),
  (33, "Biografia"),
  (34, "Vinhos"),
  (35, "Suspense"),
  (36, "Espiritualidade"),
  (37, "Agricultura"),
  (38, "Matemática"),
  (39, "Moda"),
  (40, "Autoajuda");
INSERT INTO `tbarea` (`cod_area`, `nome_area`)
VALUES (41, "Cerâmica"),
  (42, "Não-ficção"),
  (43, "Agricultura"),
  (44, "Ecologia"),
  (45, "Joalheria"),
  (46, "Pintura"),
  (47, "Ciência"),
  (48, "Física"),
  (49, "Ciência"),
  (50, "Mitologia");
INSERT INTO `tbarea` (`cod_area`, `nome_area`)
VALUES (51, "Teatro"),
  (52, "Poesia"),
  (53, "Ocultismo"),
  (54, "Pintura"),
  (55, "Agricultura"),
  (56, "Tricô"),
  (57, "Antropologia"),
  (58, "Espiritualidade"),
  (59, "Magia"),
  (60, "Medicina");
INSERT INTO `tbarea` (`cod_area`, `nome_area`)
VALUES (61, "Contos"),
  (62, "Fotografia"),
  (63, "Economia"),
  (64, "Arquitetura"),
  (65, "Informática"),
  (66, "Ciência"),
  (67, "Pintura"),
  (68, "Saúde"),
  (69, "Autobiografia"),
  (70, "Religião");
INSERT INTO `tbarea` (`cod_area`, `nome_area`)
VALUES (71, "Gastronomia"),
  (72, "Fitness"),
  (73, "Biografia"),
  (74, "Romance"),
  (75, "Ecologia"),
  (76, "Ficção"),
  (77, "Moda"),
  (78, "Folclore"),
  (79, "Dança"),
  (80, "Biografia");
INSERT INTO `tbarea` (`cod_area`, `nome_area`)
VALUES (81, "Suspense"),
  (82, "Saúde"),
  (83, "Fotografia"),
  (84, "Romance"),
  (85, "Biografia"),
  (86, "Suspense"),
  (87, "Música"),
  (88, "Política"),
  (89, "Terror"),
  (90, "Astronomia");
INSERT INTO `tbarea` (`cod_area`, `nome_area`)
VALUES (91, "Zoologia"),
  (92, "Fantasia"),
  (93, "Autobiografia"),
  (94, "Ocultismo"),
  (95, "Cinema"),
  (96, "Terror"),
  (97, "Cerâmica"),
  (98, "Arqueologia"),
  (99, "Filosofia"),
  (100, "Geografia");